version: "3.1"

networks:
  app-tier-blog:
    driver: bridge

services:
    api:
      container_name: blog-api
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
          - "8001:8001"
      working_dir: /usr/app
      volumes:
          - .:/usr/app
      networks:
        - app-tier-blog
      command: python manage.py

    postgres:
      container_name: blog-db
      working_dir: /usr/app
      volumes:
         - postgres_data:/var/lib/postgresql/data
      image: postgres
      environment:
        POSTGRES_USER: blog
        POSTGRES_PASSWORD: blog
        POSTGRES_DB : blog
        security_opt:
      networks:
        - app-tier-blog
      ports:
          - "5432:5432"
    
volumes:
  postgres_data: